### PR TITLE
Deobfuscation

### PR DESCRIPTION
**Pull request by robin-swift**

### CODE REVIEW

**Comment by robin-swift** [comment]
@JoshVarga Do you know where this originally comes from?

 Deobfuscating this mess should be a priority, but since the code _already_ doesn't work right (try `./embroider test01.csv test01.hus && ./embroider test01.hus test01_processed.csv && cat test*.csv`, it doesn't encode/decode properly).

Perhaps it's safer to strip this out entirely and do more research into the format, rather than attempt to correct broken code that's heavily obfuscated? I'd even put in the labour to manually work out the encoding based on some hus source files if we can just pull this code out.

**Comment by robin-swift** [comment]
So the format is documented [here]( http://www.jasonweiler.com/HUSandVIPFileFormatInfo.html). Quoting:

> The section is compressed using the proprietary ArchiveLib compression library made by Greenleaf Software (http://www.greenleafsoft.com). This library supports several different compression schemes, but the one used in this case is called AL_GREENLEAF_LEVEL_4. Once decompressed, the data should be exactly NumberOfStitches bytes in length with each byte sequentially representing one stitch of the pattern. 

Which is repeated for stitch x then stitch y giving 3 sections in the same encryption.

[Chasing this further](https://stackoverflow.com/questions/7852670/greenleaf-archive-library) the specifics have already been hashed out by the pyembroidery dev so we can translate that back into C for our more embedded systems friendly library and give a attribution at the top of the file to the [specific file we translated](https://github.com/EmbroidePy/pyembroidery/blob/master/pyembroidery/EmbCompress.py) (which is under the compatible MIT license).

Cheers,

Robin

**Comment by robin-swift** [comment]
I'm working on that translation, here's the attribution I'd use:
```
/*
    Thanks to Jason Weiler for describing the binary formats of the HUS and
    VIP formats at:
    
    http://www.jasonweiler.com/HUSandVIPFileFormatInfo.html

    Further thanks to github user tatarize for solving the mystery of the
    compression in:
    
    https://github.com/EmbroidePy/pyembroidery
    
    with a description of that work here:
    
    https://stackoverflow.com/questions/7852670/greenleaf-archive-library

    This is based on their work.
*/
```

**Comment by JoshVarga** [comment]
This has worked, I will review what has changed. Originally I found that the greenleaf software was being used, but no longer exists. I was able to mimic what the original code was doing, but never spent the time to fully understand it. Tatarize took the original functioning code and ported it. I am not sure who deobfuscated the code. We may be able to port the deobfuscated code back.

**Pull request merged**
