### PR TITLE
Fixing multiple definitions errors (GCC build on GNU/Linux)

### PR DESCRIPTION
**Pull request by robin-swift**
Hi,

So, I had issues building libembroidery on Debian and after a bit of reading into it I found that the issue is probably compiler specific.

I've got a patch that can make build cleanly and more memory secure in practice, but I've not submitted before so I hope this is presented correctly.

Cheers,

Robin

### CODE REVIEW

**Comment by GraniteJV** [comment]
This looks good so far I am going to run a few checks on Windows, and Mac before accepting the full merge.

**Comment by JoshVarga** [comment]
This looks good so far I am going to run a few checks on Windows, and Mac before accepting the full merge.

**Comment by robin-swift** [comment]
Oh, I'm new to GH so a whole bunch of commits have been thrown on the end here that are for different purposes. I'm not sure how to separate these out.

The CMake build _replacing_ the QMake build for example is a change that may not be to your taste and should be it's own PR?

I could make a new branch for these changes or you can just alter the commits above?

Thanks for getting back to me.

**Comment by robin-swift** [comment]
Right, just looked it up. That should be easier to test and review. (It was my misunderstanding of git merge that dumped all my other changes on the end.)

**Review by robin-swift — COMMENTED** [review]
Separated out CMake build from bugfix

**Comment by robin-swift** [comment]
This was fixed by #27 or some other accepted PR, so I'll close it.

**Pull request closed without merging**
