### PR TITLE
function inlining, simplification

### PR DESCRIPTION
**Pull request by robin-swift**

### CODE REVIEW

**Comment by JoshVarga** [comment]
@robin-swift I see the EMBEDDED define, can you send me an email to josh.varga@gmail.com I am curious about your use-case, and wanted to know how I could help.

**Comment by robin-swift** [comment]
Oh that should be ARDUINO, I'll get that in the other PR (see #91 )

**Comment by robin-swift** [comment]
Based on reading the code and bits of docs we have I thought we were working under the assumption of an embedded version that would run within 32kb of code on an Arduino?

**Comment by robin-swift** [comment]
I personally don't have an embedded system to test this on. I've just got a Brother PES something or other that I'm using.

**Comment by JoshVarga** [comment]
That makes sense, you've been doing great work cleaning up what is here. I
was just trying to see if there is a specific use case.

**Pull request merged**
